# -*- coding: utf-8 -*-
"""DAA PRAC-7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fiR1q3XJS4IcPZmsENjWWDzndbcXfkh-
"""

# Coin Change Problem using Dynamic Programming

coins = list(map(int, input("Enter coin denominations separated by space: ").split()))

amount = int(input("Enter the amount: "))

dp = [float('inf')] * (amount + 1)

dp[0] = 0

for i in range(1, amount + 1):
    for coin in coins:
        if coin <= i:
            dp[i] = min(dp[i], dp[i - coin] + 1)

if dp[amount] == float('inf'):
    print("Change cannot be made for the given amount.")
else:
    print("Minimum number of coins required:", dp[amount])